<?php
$routes = [
    ['GET',  '/login',     'AuthController@showLogin',      null],
    ['POST', '/login',     'AuthController@login',          null],
    ['POST', '/logout',    'AuthController@logout',         '*'],

    ['GET',  '/',          'DashboardController@index',     'dashboard'],
    ['GET',  '/dashboard', 'DashboardController@index',     'dashboard'],

    ['GET',  '/users',     'ModuleController@users',        'users'],
    ['POST', '/users',     'ModuleController@createUser',   'users'],
    ['GET',  '/branches',  'ModuleController@branches',     'branches'],
    ['GET',  '/customers', 'ModuleController@customers',    'customers'],
    ['GET',  '/calendar',  'ModuleController@calendar',     'calendar'],
    ['POST', '/calendar/weddings', 'ModuleController@createWedding', 'calendar'],
    ['GET',  '/billing',           'BillingController@index',     'billing'],
    ['GET',  '/billing/create',    'BillingController@create',    'billing'],
    ['POST', '/billing/store',     'BillingController@store',     'billing'],
    ['GET',  '/billing/view',      'BillingController@show',      'billing'],
    ['GET',  '/billing/edit',      'BillingController@edit',      'billing'],
    ['POST', '/billing/update',    'BillingController@update',    'billing'],
    ['POST', '/billing/postpone',  'BillingController@postpone',  'billing'],
    ['POST', '/billing/delete',    'BillingController@destroy',   'billing'],
    ['POST', '/billing/restore',   'BillingController@restore',   'billing'],
    ['GET',  '/billing/items',     'BillingController@items',     'billing'],
    ['GET',  '/billing/customers', 'BillingController@customers', 'billing'],
    ['GET',  '/reports',   'ModuleController@reports',      'reports'],

    ['GET',  '/inventory',                 'JacketController@index',     'inventory'],
    ['GET',  '/inventory/jackets/create',  'JacketController@create',    'inventory'],
    ['POST', '/inventory/jackets/store',   'JacketController@store',     'inventory'],
    ['GET',  '/inventory/jackets/view',    'JacketController@show',      'inventory'],
    ['GET',  '/inventory/jackets/edit',    'JacketController@edit',      'inventory'],
    ['POST', '/inventory/jackets/update',  'JacketController@update',    'inventory'],
    ['POST', '/inventory/jackets/delete',  'JacketController@destroy',   'inventory'],
];