CREATE TABLE IF NOT EXISTS jackets (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    code VARCHAR(50) NOT NULL UNIQUE,
    category ENUM('groom','bestman') NOT NULL,
    showrooms VARCHAR(100) NOT NULL,
    size VARCHAR(50) NOT NULL,
    status ENUM('available','unavailable') NOT NULL DEFAULT 'available',
    quantity INT UNSIGNED NOT NULL DEFAULT 0,
    pageboy_quantity INT UNSIGNED NOT NULL DEFAULT 0,
    note TEXT NULL,
    image_1 VARCHAR(100) NULL,
    image_2 VARCHAR(100) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
